#### general settings
name: HoverNet_cTrans
train_type: gnn
desc: desc #info for this run
pkl_path: './checkpoints/BRCA/final_result/'


#### datasets
datasets:
  dataset: "BRCA"
  task: "cancer survival"
  tvt_root: "./train_split/BRCA/train_split" #optional[train_split, train_split_womix, train_split_wotopo]
  train_path: "/heterogeneous_train.csv"
  test_path: "/heterogeneous_test.csv"
  valid_path: "/heterogeneous_val.csv"
  has_graph: True
  num_workers: 16

#### Checkpoint settings & Early stopping settings
checkpoint:
  path: "./checkpoints/BRCA/"
  save_checkpoint_freq: 5
Early_stop:
  warmup: 20
  patience: 3
  stop: 40

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 20
  batch_size: 1
  loss: "nll_surv"  #optional [nll_surv, ce_surv]
  alpha: 0.4

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0001 # Learning rate
  weight_decay: 0.0005
  momentum: 0.9
  gc: 32

eval:
  explain_save_path: "./"
  visualize: False
  
#### GNN settings
GNN:
  name: "H2GT"
  out_dim: 4

  HGT:
    name: "RGCN"
    n_node_types: 6
    edge_types: ["pos", "neg"]
    num_layers: 2
    in_dim: 768
    hidden_dim: 512
    num_heads: 4
    feat_drop: 0.4

  Hyper:
    n_layers: 2
    num_heads: 4
    specific: True


