# 构建超图的config文件
graph_constructor:
  dataset: BLCA
  task: "cancer typing"
  data_root: "./data/BLCA"
  # hovernet_data_root: "./data/hovernet_json"
  h5_path: "/home/dataset3/CLAM/BLCA_processed_20X/patches/"
  wsi_path: '/home/dataset2/hmh_data/TCGA_raw/BLCA/'
  out_dir: "/home/dataset2/hmh_data/my_secpro_data/het_graph/BLCA/except_mix/"
  # normal_graph_path: "/home/dataset2/hmh_data/my_secpro_data/het_graph/new_BRCA/except_topo/"
  normal_graph_path: "/home/dataset2/hmh_data/my_secpro_data/het_graph/BLCA/except_topo/" 
  new_graph_type: "except_mix" #optional[except_topo, except_mix, None]
  encoder_name: 'kimia'
  patch_size: 256
  feature_dim: 1024
  cell_radius: 10
  tissue_radius: 7
  level: 2
  n_channel: 3
  n_node_type: 6
  verbose: 0

encoder_config:
  encoder_type: "ctrans" # optional [kimianet, ctrans]
  kimianet_model_path: '/home/hmh/weights/KimiaNetPyTorchWeights.pth'
  ctrans_model_path: '/home/hmh/weights/epoch_50.pt'
  batch_size: 64

hovernet_config:
  nr_types: 6
  mode: fast
  hovernet_model_path: '/home/hmh/weights/hovernet_fast_pannuke_type_tf2pytorch.tar'
  type_info_path: 'type_info.json'
  batch_size: 64
